routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){
    //home page
    Route::get('/dashboard/home','HomeController@dashboardIndex');
    Route::get('/dashboard/home','HomeController@index');

    //boards route ::
    //view specific board
    Route::get('/board/{board}','BoardsController@boardIndex')->name('boards.boardIndex')->middleware('hasBoard');
    //view all boards
    Route::resource('/dashboard/boards','BoardsController');

    Route::get('teams/{id}/{tab}','TeamsController@showTeam')->name('showTeam')->middleware('hasTeam');

    // view teams
    Route::get('/dashboard/team', function(){
        return view('home.team');
    });
    //show team
    Route::get('teams/{id}','TeamsController@showTeam')->name('showTeam');

    Route::Resource('team','TeamsController');
    Route::post('teams/addMember','TeamsController@addMember')->name('addMember');

    //ajax routes on board
    Route::post('/board/list/create','BoardsController@createList')->name('ajax.storeList');
    Route::post('/board/list/card/updatedue','BoardsController@updateDue')->name('ajax.updateCardDue');
    Route::post('/board/list/card/updatedes','BoardsController@updateDes')->name('ajax.updateCardDes');
    Route::get('/board/list/card/get','BoardsController@getCard')->name('ajax.getCard');
    Route::post('/board/list/card/checklist/insert','ChecklistsController@insertChecklist')->name('ajax.insertChecklist');
    Route::post('/board/list/card/checklist/update','ChecklistsController@updateChecklist')->name('ajax.updateChecklist');
    Route::post('/board/list/create','BoardsController@createList')->name('ajax.storeList');
    Route::post('/board/list/card/create','CardsController@createCard')->name('ajax.storeCard');
    Route::post('/board/list/card/create/member','CardsController@addMemberToCard')->name('ajax.addMemberToCard');
    Route::post('/board/invite/member','BoardsController@addMemberToBoard')->name('ajax.addMemberToBoard');
    Route::post('/board/changeVisibility','BoardsController@changeVisibility')->name('ajax.changeVisibility');

    //ajax route on team
    Route::post('teams/changeVisibility','TeamsController@changeVisibility')->name('ajax.changeVisibility');
    Route::post('teams/addMembers','TeamsController@addMembers')->name('ajax.addMembers');
    Route::post('teams/storeMyTeam','TeamsController@storeMyTeam')->name('ajax.storeMyTeam');

});

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Board;
use App\notification;
use App\Team;
use App\Team_Type;
use App\User;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $types = Team_Type::all();
        $notifications = notification::where('to_user','=',auth()->user()->id)->get();
        $teams = auth()->user()->teams;
        $personalBoards = Board::where(['type'=>'personal','user_id'=>auth()->id()])->get()->take(5);
        return view('home.home',compact(['types','notifications','teams','personalBoards']));
    }
}

resources/views/home/board.blade.php
@extends('layouts.dashboard')
@section('style')
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
<style>

</style>
@endsection
@section('content')
<div>
    <div class="section-type col-md-7">
        <p><i class="fa fa-clock-o"></i>&nbsp;&nbsp;Recently Viewed</p>
    </div>
    <div class="boards mt-3">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-3">
                    <a href="" class="card" style="background-color:blue">
                        <p>Hello</p>
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="mt-4 section-type col-md-12">
        <p><i class="fa fa-user-o"></i>&nbsp;&nbsp;Personal Boards</p>
    </div>

        <div class="boards mt-3">
            <div class="col-md-12">
                <div class="row">
                    @foreach ($boardsPersonal as $board)

                    <div class="col-md-3">
                        <input type="hidden" name="board_id" id="board_id" value="{{$board->id}}">
                    <a href="{{route('boards.boardIndex',$board->id)}}" class="card {{$board->color}}">
                            <p>{{$board->name}}</p>
                        </a>
                    </div>
                    @endforeach

                    <div class="col-md-3">
                        <button type="button" data-toggle="modal" data-target="#exampleModal" class="card justify-content-center create">
                            <p class="text-center m-0">Create New board</p>
                        </button>

                    </div>

                </div>
            </div>
        </div>

    @for($i=0;$i<count($boardsTeam);$i+=2)

    <div class="mt-4 section-type col-md-12 d-flex justify-content-between">
        <div>
            <p><i class="fa fa-users"></i>&nbsp;&nbsp;{{$boardsTeam[$i]->name}}</p>
        </div>
        <div class=" ">
            <a href="{{route('showTeam',[$boardsTeam[$i],'boards'])}}" class="board-info d-inline-block mr-1"><i class="fa fa-clipboard"></i>&nbsp;&nbsp;Boards</a>
            <a href="{{route('showTeam',[$boardsTeam[$i],'members'])}}" class="board-info d-inline-block mr-1"><i class="fa fa-user"></i>&nbsp;&nbsp;Members({{ ($boardsTeam[$i]->users)->count() }})</a>
            <a href="{{route('showTeam',[$boardsTeam[$i],'settings'])}}" class="board-info d-inline-block mr-1"><i class="fa fa-gear"></i>&nbsp;&nbsp;Settings</a>
        </div>
    </div>

    <div class="boards mt-3">
        <div class="col-md-12">
            <div class="row">
                @for ($j=0;$j<count($boardsTeam[$i+1]);$j++)

                <div class="col-md-3">
                    <a href="{{route('boards.boardIndex',$boardsTeam[$i+1][$j]->id)}}" class="card {{$boardsTeam[$i+1][$j]->color}}">
                        <input type="hidden" id="board_id" name="board_id" value="{{$boardsTeam[$i+1][$j]->id}}">
                        <p>{{$boardsTeam[$i+1][$j]->name}}</p>
                    </a>
                </div>
                @endfor

                <div class="col-md-3">
                <button type="button" data-toggle="modal" data-target="#exampleModal" data-id ="{{$boardsTeam[$i]->id}}" class="card justify-content-center create">
                        <p class="text-center m-0">Create New board</p>
                    </button>

                </div>

            </div>
        </div>
    </div>

    @endfor

</div>


</div>


{{-- <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog mt-5 py-5" role="document">
                <div class="modal-content">
                    <form action="{{ route('boards.store') }}" method="POST">
                        @csrf
                        <div>
                    <div class="row">
                        <div class="col-md-6 ml-2 m-0 bg-color" style="background-color: blue">
                            <div class="pt-2 form-group m-0">
                                <div class="d-flex justify-content-between">
                                    <input type="hidden" name="color_code" id="color_code" value="blue">
                                    <input type="text" name="name" id="name" placeholder="Add Board title" class="input bg-none form-control">
                                    <button type="button" class="btn btn-close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true" class="text-white" style="font-size: 16px">&times;</span>
                                    </button>
                                </div>
                            </div>
                            <div class="form-group col-md-6 p-0 m-0 mb-1">
                                <select name="team_id" id="team_id" class="bg-none input form-control">
                                    <option class="text-black" value="personal">Personal</option>

                                    @foreach ($allTeams as $team)
                                        <option class="text-black" value="{{$team->id}}">{{$team->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="p-0  form-group col-md-6  m-0 mb-1">
                                <select name="visibility" id="visibility" class="bg-none input form-control">
                                    <option class="text-black" value="private"><i class="fa fa-lock"></i>Private</option>
                                    <option class="text-black" value="public"><i class="fa fa-lock"></i>Public</option>
                                </select>
                            </div>
                        </div>
                        <form action="" method="POST">
                            @csrf
                            {{-- <div class="col-md-3 m-0 colors form-group" >
                                <div class="row pl-2">
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div  class="color blue"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="red"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="brown"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="green"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="pink"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="black"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div class="orange"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div  class="purple"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div  class="grey"></div>
                                    </div>
                                </div>
                            </div> --}}
                        </form>
                    </div>
                <div class="form-group m-0">
                    <button type="submit" class=" btn btn-success form-control" style="width: 100px">Create board</button>
                </div>
            </div>
            </form>

        </div>
    </div>
END MODAL --}}
@endsection
@section('script')
    <script>

    </script>
@endsection

resources/views/home/home.blade.php
@extends('layouts.dashboard')
@section('style')
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
@endsection
@section('content')
<div class="ml-5">
    <div class="row">
        <div class="col-md-6 p-0">
            <div class="bg p-2">
                <div class="pl-1 list">
                    <p>complete this task</p>
                    <div class="d-flex  justify-content-between">
                        <p class="d-inline-block bg-danger mb-2 p-1  text-white"><i class="fa fa-clock-o"></i> 2 Aug</p>
                        <div class="avatar p-1 text-center">
                            <span class="avat p-1">AG</span>
                        </div>
                    </div>
                </div>
                <span class="text-white">TP2: new</span>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6 card-action">
            <div class="d-flex p-3 justify-content-between">
                <p class="d-inline-block"><i class="fa fa-clock-o pr-1"></i>Due 2 Aug at 22:59</p>
                <p class="d-inline-block"><i class="fa fa-ellipsis-h"></i></p>
            </div>
            <div class="row mb-2">
                <div class="col-md-6 "><div class="p-1 status text-center"><i class="fa fa-check"></i> Complete</div></div>
                <div class="col-md-6 "> <div class="p-1 status text-center"><i class="fa fa-close"></i> Dismiss</div></div>
            </div>
        </div>
    </div>
</div>
@endsection
@section('script')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
@endsection

resources/views/home/team.blade.php
@extends('layouts.app')
@section('content')
<section id="team">
    <div class="team-info">
        <div class="image">
            <i class="fa fa-users" aria-hidden="true"></i>
        </div>
        <div id="other-infos" class="other-info">
            <div class="team-name"><h3>{{$team->name}}</h3></div>
            <span class="team-visibility">
                @if ($team->visibility == "private")
                    <i class="fa fa-lock" aria-hidden="true"></i> Private
                @else
                    <i class="fa fa-unlock" aria-hidden="true"></i> Public
                @endif
            </span>
            <div class="description">{{$team->description}}</div>
            <div class="btn btn-light mt-2" type="button" id="edit-team-btn"><i class="fa fa-pencil" aria-hidden="true"></i> Edit team Profile</div>
        </div>
        <div id="edit-team" class="d-none">
            <div class="wrapper">
                <form action="{{route('team.update',$team->id)}}" method="post">
                    @csrf
                    @method('PUT')
                    <label for="" class="dark-text">Team Name</label>
                    <input type="text" class="my-input" name="name" value="{{$team->name}}">
                    <label for="" class="dark-text pt-2">Team Type</label>
                    <select name="type_id" id="type_id" class="my-input">
                        @foreach ($types as $type)
                            <option value="{{$type->id}}" {{($type->id == $team->type_id) ? 'selected' : ''}}>{{$type->name}}</option>
                        @endforeach
                    </select>
                    <label for="" class="dark-text pt-2">description</label>
                    <textarea name="description" id="team-description" cols="30" rows="5" class="my-input">{{$team->description}}</textarea>
                    <button type="submit" class="btn btn-success">save</button>
                    <div id="cancel-edit-team" class="btn">cancel</div>
                </form>
            </div>
        </div>
    </div>
    <div class="team-setting mt-4">
        <ul class="nav nav-tabs my-nav-tabs justify-content-center" id="myTab" role="tablist">
            <li class="nav-item">
                <a class="nav-link {{($tab=="null")? 'active':(($tab=="boards")?'active':'')}}" id="boards-tab" data-toggle="tab" href="#boards" role="tab" aria-controls="boards" aria-selected="true">Boards</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{($tab=="members")?'active':''}}" id="Members-tab" data-toggle="tab" href="#Members" role="tab" aria-controls="Members" aria-selected="false">Members</a>
            </li>
            <li class="nav-item">
                <a class="nav-link {{($tab=="settings")?'active':''}}" id="Settings-tab" data-toggle="tab" href="#Settings" role="tab" aria-controls="Settings" aria-selected="false">Settings</a>
            </li>
        </ul>
        <div class="tab-content team-container mt-4" id="myTabContent">
            <div class="tab-pane fade {{($tab=="null")? 'show active':(($tab=="boards")?'show active':'')}}" id="boards" role="tabpanel" aria-labelledby="boards-tab">
                @foreach ($boards as $board)
            <a href="{{route('boards.boardIndex',$board)}}" >
                        <div class="team-board board mt-2 {{$board->color}}">
                            <h5>{{$board->name}}</h5>
                        </div>
                    </a>
                @endforeach
                <div class="board create-board mt-2 ">
                    <button type="button" data-toggle="modal" data-target="#exampleModal" class="m-0 h-100 card justify-content-center create">
                        <p class="text-center m-0">Create New board</p>
                    </button>

                </div>
            </div>
            <div class="tab-pane fade members {{($tab=="members")?'show active':''}}" id="Members" role="tabpanel" aria-labelledby="Members-tab">
                <h3>Invite Your Team</h3>
                <p>Trello makes teamwork your best work. Invite your new team members to get going!</p>
                <h5>Team Members</h5>

                    <form action="{{route('addMember')}}" method="POST">
                        @csrf
                        <div class="d-flex">
                            <input type="hidden" name="team_id" value="{{$team->id}}" class="d-none">
                            <input type="text" name="email" id="search-members" placeholder="e.g. clarissian@cloud.ci">
                            <button type="submit" id="invite-btn" class="btn btn-primary ml-2 disabled-btn" disabled>Invite</button>
                        </div>
                    </form>

                <p><strong>Pro Tip!</strong> Paste as many emails here as needed.</p>
            </div>
            <div class="tab-pane fade team-settings {{($tab=="settings")?'show active':''}}" id="Settings" role="tabpanel" aria-labelledby="Settings-tab">
                <h6>Team Visibility</h6>
                <div class="visibility justify-content-between">
                    <i class="fa fa-lock" aria-hidden="true"></i> <strong>Private</strong>  - This team is private. It's not indexed or visible to those outside the team.
                    <div class="btn btn-light" id="change-visibility">change</div>
                </div>
            </div>
        </div>
    </div>

    <div id="visibility-option" class="d-none">
        <h5 class="text-center">Select Team Visibility</h5>
        <hr>
        <ul id="visibility-list">
            <li id="private-Visibility-option" class="v-option" data-id="private">
                <div class="d-flex"><i class="fa fa-lock" aria-hidden="true"></i>private
                @if ($team->visibility == "private")
                    <i class="fa fa-check" aria-hidden="true"></i>
                @endif
                </div>
                <span>
                    This team is private.It's not indexed or visible to those outside the team
                </span>
            </li>
            <li id="public-Visibility-option" class="v-option" data-id="public">
                <div class="d-flex"><i class="fa fa-unlock" aria-hidden="true"></i> Public
                @if ($team->visibility == "public")
                    <i class="fa fa-check" aria-hidden="true"></i>
                @endif
                </div>
                <span>
                    This team is public. It's visible to anyone with the link and will show up in search engines like Google. Only those invited to the team can add and edit team boards.
                </span>
            </li>
        </ul>
    </div>
</section>

@endsection
@section('script')
    <script>
        $('body').css('background-color','#fff');
    </script>
    <script>
        $('#edit-team-btn').click(function(){
            $('#other-infos').toggleClass('d-none');
            $('#edit-team').toggleClass('d-block');
        })
        $('#cancel-edit-team').click(function(){
            $('#other-infos').toggleClass('d-none');
            $('#edit-team').toggleClass('d-block');
        })
        $("#search-members").keyup(function(){
            var value = $.trim($("#search-members").val());
            if(value != ""){
                $("#invite-btn").removeAttr("disabled");
                $("#invite-btn").removeClass("disabled-btn");
            }else{
                $("#invite-btn").attr("disabled",true);
                $("#invite-btn").addClass("disabled-btn");
            }
        });
        $("#change-visibility").click(function(){
            $('#visibility-option').toggleClass('d-none');
        });
    </script>
    <script>
        $('#visibility-list').on("click","li",function (e) {

            var newVisibility = $(this).data("id");
            var teamId = "{{$team->id}}";
            var route = "{{ route('ajax.changeVisibility') }}";
            $.ajax({
                url: route,
                method: "POST",
                data:{
                    _token: "{{ csrf_token() }}",
                    'teamId': teamId,
                    'visibility':newVisibility
                },
                dataType: 'json',
                success: function(success){
                    if(success == "success"){
                        if(newVisibility == "private"){
                            $("#private-Visibility-option").html(`
                                <div class="d-flex"><i class="fa fa-lock" aria-hidden="true"></i>private
                                <i class="fa fa-check" aria-hidden="true"></i>
                                </div>
                                <span>
                                    This team is private.It's not indexed or visible to those outside the team
                                </span>
                            `);
                            $('#public-Visibility-option').html(`
                                <div class="d-flex"><i class="fa fa-unlock" aria-hidden="true"></i> Public
                                </div>
                                <span>
                                    This team is public. It's visible to anyone with the link and will show up in search engines like Google. Only those invited to the team can add and edit team boards.
                                </span>
                            `);
                            $('.team-visibility').html(`
                                <i class="fa fa-lock" aria-hidden="true"></i>private
                            `);
                        }else if(newVisibility == "public"){
                            $("#private-Visibility-option").html(`
                                <div class="d-flex"><i class="fa fa-lock" aria-hidden="true"></i>private
                                </div>
                                <span>
                                    This team is private.It's not indexed or visible to those outside the team
                                </span>
                            `);
                            $('#public-Visibility-option').html(`
                                <div class="d-flex"><i class="fa fa-unlock" aria-hidden="true"></i> Public
                                    <i class="fa fa-check" aria-hidden="true"></i>
                                </div>
                                <span>
                                    This team is public. It's visible to anyone with the link and will show up in search engines like Google. Only those invited to the team can add and edit team boards.
                                </span>
                            `);
                            $('.team-visibility').html(`
                                <i class="fa fa-unlock" aria-hidden="true"></i>public
                            `);
                        }
                        $('#visibility-option').toggleClass('d-none');
                    }
                }
            });
        });
    </script>
@endsection