routes/web.php
<?php

use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::middleware(['auth'])->group(function(){
    //home page
    Route::get('/dashboard/home','HomeController@dashboardIndex');
    Route::get('/dashboard/home','HomeController@index');

    //boards route ::
    //view specific board
    Route::get('/board/{board}','BoardsController@boardIndex')->name('boards.boardIndex')->middleware('hasBoard');
    //view all boards
    Route::resource('/dashboard/boards','BoardsController');

    Route::get('teams/{id}/{tab}','TeamsController@showTeam')->name('showTeam')->middleware('hasTeam');

    // view teams
    Route::get('/dashboard/team', function(){
        return view('home.team');
    });
    //show team
    Route::get('teams/{id}','TeamsController@showTeam')->name('showTeam');

    Route::Resource('team','TeamsController');
    Route::post('teams/addMember','TeamsController@addMember')->name('addMember');

    //ajax routes on board
    Route::post('/board/list/create','BoardsController@createList')->name('ajax.storeList');
    Route::post('/board/list/card/updatedue','BoardsController@updateDue')->name('ajax.updateCardDue');
    Route::post('/board/list/card/updatedes','BoardsController@updateDes')->name('ajax.updateCardDes');
    Route::get('/board/list/card/get','BoardsController@getCard')->name('ajax.getCard');
    Route::post('/board/list/card/checklist/insert','ChecklistsController@insertChecklist')->name('ajax.insertChecklist');
    Route::post('/board/list/card/checklist/update','ChecklistsController@updateChecklist')->name('ajax.updateChecklist');
    Route::post('/board/list/create','BoardsController@createList')->name('ajax.storeList');
    Route::post('/board/list/card/create','CardsController@createCard')->name('ajax.storeCard');
    Route::post('/board/list/card/create/member','CardsController@addMemberToCard')->name('ajax.addMemberToCard');
    Route::post('/board/invite/member','BoardsController@addMemberToBoard')->name('ajax.addMemberToBoard');
    Route::post('/board/changeVisibility','BoardsController@changeVisibility')->name('ajax.changeVisibility');

    //ajax route on team
    Route::post('teams/changeVisibility','TeamsController@changeVisibility')->name('ajax.changeVisibility');
    Route::post('teams/addMembers','TeamsController@addMembers')->name('ajax.addMembers');
    Route::post('teams/storeMyTeam','TeamsController@storeMyTeam')->name('ajax.storeMyTeam');

});

resources/views/layouts/partials/_header-scripts.blade.php
<script>
    $('#close-notification-modal').click(function(e){
        $('#notification-panel').toggleClass('d-block').toggleClass('d-none');
    });
    $('#notification-btn').click(function(e){
        $('#notification-panel').toggleClass('d-block').toggleClass('d-none');
    });
    $('#notification-panel').click(function(e){
        $('#notification-panel').toggleClass('d-block').toggleClass('d-none');
        $('#notification-btn').removeClass('new-notification');
    });
    $('#notification-panel .wrapper').click(function(e){
        e.stopPropagation();
    });

    // add team modal
    $("#team-name").keyup(function(){
        var value =$("#team-name").val();
        value = $.trim(value);
        if(value == ""){
            $(".my-submit-btn").attr("disabled",true);
            $(".my-submit-btn").addClass("disabled-btn");
        }else{
            $(".my-submit-btn").removeAttr("disabled",true);
            $(".my-submit-btn").removeClass("disabled-btn");
        }
    });

    //add member modal
    $("#members").keyup(function(){
        var value =$("#members").val();
        value = $.trim(value);
        if(value == ""){
            $(".member-submit-btn").attr("disabled",true);
            $(".member-submit-btn").addClass("disabled-btn");
        }else{
            $(".member-submit-btn").removeAttr("disabled",true);
            $(".member-submit-btn").removeClass("disabled-btn");
        }
    });

    $("#team-submit").click(function(e){
        var route = "{{ route('team.store') }}";
        var team = $("#team-name").val();
        var description = $('#team-description').val();
        var type = $( "#team-type option:selected" ).text();
        $('#team-name').val("");
        $('#team-description').val("");

        $.ajax({
            url: route,
            method: "POST",
            data:{
                _token: "{{ csrf_token() }}",
                'team_name':team,
                'team_type':type,
                'team_description':description,
            },
            dataType: 'json',
            success: function(success){
                $('#add-member-to-team').val(success);
                $('#create-team').toggleClass('d-none').toggleClass('d-block');
                $('#add-members').toggleClass('d-none').toggleClass('d-block');
            }
        });
    });

    $('#member-submit').click(function (e) {
        var members = $("#members").val();
        var team_id = $('#add-member-to-team').val();
        var route = "{{ route('ajax.addMembers') }}";
        $("#members").val("");
        $.ajax({
            url:route,
            method:"POST",
            data:{
                _token: "{{ csrf_token() }}",
                'members': members,
                'team_id': team_id
            },
            dataType: 'json',
            success:function(success){
                $('#add-members').toggleClass('d-none').toggleClass('d-block')
            }
        })
    });


    $("#create-team-option").click(function(){
        $('#create-block').toggleClass('d-block').toggleClass('d-none');
        $('#create-team').toggleClass('d-block').toggleClass('d-none');
    });
    $("#create-team-btn").click(function(){
        $('#create-team').toggleClass('d-block').toggleClass('d-none');
    });
    $("#close-create-team").click(function(){
        $('#create-team').toggleClass('d-block').toggleClass('d-none');
    });


    $('#create-team .wrapper').click(function(e){
        e.stopPropagation();
    });
    $('#create-team').click(function(){
        $('#create-team').toggleClass('d-block').toggleClass('d-none')
    });

    $("#close-member-modal").click(function(){
        $('#add-members').toggleClass('d-block').toggleClass('d-none');
    });
    $("#close-member-modal-btn").click(function(){
        $('#add-members').toggleClass('d-block').toggleClass('d-none');
    });
    $('#add-members .wrapper').click(function(e){
        e.stopPropagation();
    });
    $('#add-members').click(function(){
        $('#add-members').toggleClass('d-block').toggleClass('d-none');
    });
</script>

resources/views/layouts/partials/_header.blade.php
<section id="header">
    <div class="wrapper">
        <div>
            <a href="{{route('home')}}" class="home element-alignments">
                <i class="fa fa-home" aria-hidden="true"></i>
            </a>
            <div class="boards element-alignments" id="board-btn">
                <i class="fa fa-trello" aria-hidden="true"></i> Boards
            </div>
            <div class="search element-alignments">
                <input type="text" class="search-input"> <i class="fa fa-search" aria-hidden="true"></i>
            </div>
        </div>
        <div>
            <div class="icon">
                <i class="fa fa-trello" aria-hidden="true"></i> Trello
            </div>
        </div>
        <div>
            <div class="create-btn element-alignments">
                <i class="fa fa-plus" aria-hidden="true"></i>
            </div>
            <div class="notification element-alignments" id="notification-btn">
                <i class="fa fa-bell bell" aria-hidden="true"></i>
            </div>
            <div class="logout-btn profile element-alignments">
                <i class="fa fa-user-circle-o" aria-hidden="true"></i>
            </div>
        </div>
    </div>

    <div id="boards-search" class="d-none">
        <div class="close-div pull-right">
            X
        </div>
        <div class="clearfix"></div>
        <div class="boards">
            <ul>
                <li class="board-heading mt-2">
                    <a data-toggle="collapse" href="#collapsePersonal" role="button" aria-expanded="true" aria-controls="collapsePersonal" class="boards-header">
                        <i class="fa fa-trello" aria-hidden="true"></i> personal Boards
                    </a>
                </li>
                <div class="" id="collapsePersonal">
                    <ul>
                        @foreach ($personalBoards as $board)
                            <li class="boards-list">
                                <a href="{{route('boards.boardIndex',$board->id)}}"><span class="white-space">&ThickSpace;&ThickSpace;&ThickSpace;&ThickSpace;</span> <span class="ml-2"></span>{{$board->name}}</a>
                            </li>
                        @endforeach
                    </ul>
                    <a href="{{route('boards.index')}}">Show All</a>
                </div>
            </ul>
        </div>
    </div>

    <div id="create-block" class="d-none">
        <div class="text-center header mt-1">
            <div class="close-create-div pull-right p-1 mr-2">
                X
            </div>
            <h6>Create</h6>
        </div>
        <hr class="hr-primary">
        <div class="create-type" data-toggle="modal" data-target="#exampleModal">
            <h5><i class="fa fa-trello" id="create-board-option" aria-hidden="true"></i> Create Board</h5>
            <div class="light-fonts">
                <p class="d-inline-block">A board is made up of cards ordered on lists. Use it to manage projects, track information, or organize anything.</p>
            </div>
        </div>
        <div class="create-type mt-1"  id="create-team-option">
            <h5><i class="fa fa-users" aria-hidden="true"></i> Create Team</h5>
            <div class="light-fonts">
                <p class="d-inline-block">A board is made up of cards ordered on lists. Use it to manage projects, track information, or organize anything.</p>
            </div>
        </div>
    </div>
    <div id="notification-panel" class="d-none">
        <div class="wrapper">
            <div class="content" id="notification-cards">
                <div class="notification-header text-center">
                    <p>Notifications</p>
                    <div id="close-notification-modal" class="close-btn">X</div>
                </div>
                <hr>

                <div id="notification-list">
                    @foreach ($notifications as $notification)
                        <div class="container mt-3" id="notification-card_{{$notification->card_id}}">
                            <div class="row">
                                <div class="col-md-12 p-2">
                                    <div class="bg p-2">
                                        <a href="{{route('boards.boardIndex',$notification->card->list->board)}}">
                                            <div class="pl-1 list">
                                                <p>{{$notification->card->name}}</p>
                                                <div class="d-flex  justify-content-between" id="notification-due-date">
                                                    @if ($notification->card->due_date)
                                                        <p id="due-content" class="d-inline-block bg-danger mb-2 p-1 px-2 text-white">
                                                            <i class='fa fa-clock-o'></i>&MediumSpace;{{date('d-m', strtotime($notification->card->due_date))}}
                                                        </p>
                                                    @else
                                                        <div id="blank-div"></div>
                                                    @endif
                                                    <div class="avatar p-1 text-center mb-2">
                                                        @foreach ($notification->card->users as $user)
                                                            <img src="{{$user->avatar}}" alt="">
                                                        @endforeach
                                                    </div>
                                                </div>
                                            </div>
                                        </a>
                                        <span class="text-white">{{$notification->card->list->board->name}}: {{$notification->card->list->name}}</span>
                                    </div>
                                </div>
                            </div>
                            <div class="row px-2">
                                <div class="col-md-12 card-content card-action">
                                    <div class="p-3">
                                        <div class="d-flex" id="sender-card-user" data-user-id="1">
                                            <div class="avatar text-center">
                                                <img src="{{$notification->fromUser->avatar}}" alt="">
                                            </div>
                                            <strong><p class="ml-1">{{$notification->fromUser->name}}</p></strong>
                                        </div>
                                        <div id="notification-actions_{{$notification->card_id}}" data-card-id="{{$notification->card_id}}">
                                            @foreach ($notification->messages as $message)
                                                @if ($message->type == "add-user")
                                                    <a href="{{route('boards.boardIndex',$notification->card->list->board)}}"><p class="d-block"><i class="fa fa-chevron-right pr-1" aria-hidden="true"></i>Added You</p></a>
                                                @elseIf($message->type == "add-checklist")
                                                    <a href="{{route('boards.boardIndex',$notification->card->list->board)}}"><p class="d-block"><i class="fa fa-chevron-right pr-1" aria-hidden="true"></i>Added Checklist</p></a>
                                                @elseIf($message->type == "due-date")
                                                    <a href="{{route('boards.boardIndex',$notification->card->list->board)}}"><p class="d-block"><i class="fa fa-clock-o pr-1 pr-1"></i>Added due date Due 2 Aug at 22:59</p></a>
                                                @elseIf($message->type == "remove-user")
                                                    <a href="{{route('boards.boardIndex',$notification->card->list->board)}}"><p class="d-block"><i class="fa fa-chevron-right pr-1" aria-hidden="true"></i>Removed You</p></a>
                                                @endif
                                            @endforeach
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    @endforeach
                </div>
            </div>
        </div>
    </div>



    <!-- Modal -->
    <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <form action="{{ route('boards.store') }}" method="POST">
                        @csrf
                        <div>
                    <div class="row">
                        <div class="col-md-6 ml-2 m-0 bg-color" style="background-color: blue">
                            <div class="pt-2 form-group m-0">
                                <div class="d-flex justify-content-between">
                                    <input type="hidden" name="color_code" id="color_code" value="blue">
                                    <input type="text" name="name" id="name" placeholder="Add Board title" class="input bg-none form-control">
                                    <button type="button" class="btn btn-close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true" class="text-white" style="font-size: 16px">&times;</span>
                                    </button>
                                </div>
                            </div>
                            <div class="form-group col-md-6 p-0 m-0 mb-1">
                                <select name="team_id" id="team_id" class="bg-none input form-control">
                                    <option class="text-black" value="personal">Personal</option>
                                    @foreach ($teams as $team)
                                        <option class="text-black" value="{{$team->id}}">{{$team->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                            <div class="p-0  form-group col-md-6  m-0 mb-1">
                                <select name="visibility" id="visibility" class="bg-none input form-control">
                                    <option class="text-black" value="private"><i class="fa fa-lock"></i>Private</option>
                                    <option class="text-black" value="public"><i class="fa fa-lock"></i>Public</option>
                                </select>
                            </div>
                        </div>
                        <form action="" method="POST">
                            @csrf
                            <div class="col-md-3 m-0 colors form-group" >
                                <div class="row pl-2">
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="blue"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="red"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="brown"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="green"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="pink"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="black"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="orange"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="purple"></div>
                                    </div>
                                    <div class="color-card col-md-4 p-0 pt-2">
                                        <div id="color"  class="grey"></div>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                <div class="form-group m-0">
                    <button type="submit" class=" btn btn-success form-control" style="width: 100px">Create board</button>
                </div>
            </div>
            </form>

        </div>
    </div>
{{-- END MODAL --}}
</section>

resources/views/layouts/partials/_mainScripts.blade.php
@auth
<script>
    var user_id = {{auth()->user()->id}};
    Echo.private(`notify.${user_id}`)
    .listen('NotificationEvent', (e) => {
        if($('#notification-panel').hasClass('d-none')){
            $('#notification-btn').addClass('new-notification');
        }
        var id = '#notification-actions_'+e.message[3].id;
        var card_id = $(id).data('card-id');
        console.log(e);
        if(card_id == e.message[3].id){
            addToNotification(e,id,card_id);
        }else{
            addNewNotification(e);
        }
    });
    function addNewNotification(e){
        // console.log("new card notification");
        var imgs = "";
        for(var i=0;i<e.message[8];i++){
            imgs += `<img src="${e.message[8][i]}" alt="">`;
        }
        var sender = `<img src="${e.message[9]}" alt="">`;

        $('#notification-list').prepend(`
            <div class="container mt-3" id="notification-card_${e.message[3].id}"">
                <div class="row">
                    <div class="col-md-12 p-2">
                        <div class="bg p-2">
                            <a href=""><div class="pl-1 list">
                                <p>${e.message[3].name}</p>
                                <div class="d-flex  justify-content-between" id="notification-due-date">
                                    <div id="blank-div"></div>
                                    <div class="avatar p-1 text-center">
                                        ${img}
                                    </div>
                                </div>
                            </a>
                            </div>
                            <span class="text-white">${e.message[5].name}: ${e.message[4].name}</span>
                        </div>
                    </div>
                </div>
                <div class="row px-2">
                    <div class="col-md-12 card-content card-action">
                        <div class="p-3">
                            <div class="d-flex" id="sender-card-user" data-user-id="${e.message[6].id}">
                                <div class="avatar text-center">
                                    ${sender}
                                </div>
                                <strong><p class="ml-1">${e.message[6].name}</p></strong>
                            </div>
                            <div id="notification-actions_${e.message[3].id}" data-card-id="${e.message[3].id}">
                                <a href=""><p class="d-block"><i class="fa fa-clock-o pr-1"></i>Added you</p></a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        `);
    }
    function addToNotification(e,list,card_id){
        // console.log("add to notification");
        if(e.message[2] == "add-user"){
            // console.log(e.message[2]);
            $(list).append(`<a href=""><p class="d-block"><i class="fa fa-chevron-right pr-1" aria-hidden="true"></i>Added You</p></a>`);
        }else if(e.message[2] == "add-checklist"){
            console.log(e.message[2]);
            $(list).append(`<a href=""><p class="d-block"><i class="fa fa-chevron-right pr-1"></i>Added checklist</p></a>`);
        }
        else if(e.message[2] == "remove-user"){
            $(list).append(`<a href=""><p class="d-block"><i class="fa fa-chevron-right pr-1"></i>Removed you</p></a>`);
        }
        else if(e.message[2] == "due-date"){
            $('#due-content').remove();
            $('#blank-div').remove();
            $('#notification-due-date').prepend(`<p class="d-inline-block bg-danger mb-2 p-1 px-2 text-white" id="due-content"><i class='fa fa-clock-o'></i>  ${e.message[7]}</p>`);
            $(list).append(`<a href=""><p class="d-block"><i class="fa fa-clock-o pr-1"></i>Added due date ${e.message[7]}</p></a>`);
        }

        var id = '#notification-card_'+card_id;
        var card = $(id).html();
        $('#notification-card_'+card_id).remove();
        card = `<div class="container mt-3" id="notification-card_${e.message[3].id}"">`+card+"</div>";

        $('#notification-list').prepend(card);
    }
</script>
@endauth
<script>
        $(".color-card").click(function(e){
            var color = e.target.className;
            console.log(color);
            $(".bg-color").css("background-color",color);
            $("#color_code").val(color)

        });
        // $(".blue").click(function(){
        //     $(".bg-color").css("background-color","blue");
        //     $("#color_code").val("blue")
        // });

        // $(".red").click(function(){
        //         $(".bg-color").css("background-color","red");
        //         $("#color_code").val("red")
        // });
        // $(".brown").click(function(){
        //     $(".bg-color").css("background-color","brown");
        //     $("#color_code").val("brown")
        // });
        // $(".green").click(function(){
        //     $(".bg-color").css("background-color","green");
        //     $("#color_code").val("green")
        // });
        // $(".pink").click(function(){
        //     $(".bg-color").css("background-color","pink");
        //     $("#color_code").val("pink")
        // });
        // $(".black").click(function(){
        //     $(".bg-color").css("background-color","black");
        //     $("#color_code").val("black")
        // });
        // $(".orange").click(function(){
        //     $(".bg-color").css("background-color","orange");
        //     $("#color_code").val("orange")
        // });
        // $(".purple").click(function(){
        //     $(".bg-color").css("background-color","purple");
        //     $("#color_code").val("purple")
        // });
        // $(".grey").click(function(){
        //     $(".bg-color").css("background-color","grey");
        //     $("#color_code").val("grey")
        // });
</script>

resources/views/layouts/partials/_modal.blade.php
<div id="create-team" class="d-none mt-5 py-3">
    <div class="wrapper mb-4">
        <div id="close-create-team">X</div>
        <div class="content-wrapper row">
            <div class="create col-md-6">
                <div class="create-wrapper">
                    <h4 class="dark-text">Lets Build a Team</h4>
                    <h5>Boost your productivity by making it easier for everyone to access boards in one location.</h5>
                    <span class="label dark-text">Team Name</span>
                    <input type="text" name="team_name" id="team-name" class="my-input p-2">
                    <span class="light-text info pt-1">This is the name of your company, team or organization.</span>
                    <span class="label dark-text">Team type</span>
                    <select name="team_type" id="team-type" class="my-input p-2">
                        @foreach ($types as $type)
                            <option value="{{$type->id}}">{{$type->name}}</option>
                        @endforeach
                    </select>
                    <span class="label dark-text">Description <span class="optional-text">Optional</span></span>
                    <textarea name="team_description" id="team-description" cols="30" rows="5" class="my-input p-2"></textarea>
                    <span class="light-text pb-3 pt-1">This is the name of your company, team or organization.</span>
                    <button class="my-submit-btn disabled-btn" id="team-submit" disabled>Continue</button>
                </div>
            </div>
            <div class="image-section col-md-6 text-center">
                <img src="https://a.trellocdn.com/prgb/dist/images/organization/empty-board.286f8fc83e01c93ed27e.svg" alt="">
            </div>
        </div>
    </div>
</div>

<div id="add-members" class="d-none mt-5 pt-5">
    <div class="wrapper">
        <div id="close-member-modal" class="close-btn">X</div>
        <div class="content-wrapper row">
            <div class="create col-md-6">
                <div class="create-wrapper">
                    <input type="hidden" name="team_id" id="add-member-to-team">
                    <h4 class="dark-text">Invite Your Team</h4>
                    <h5 class="light-text">Trello makes your teamwork best work. Invite your new team members to get going!</h5>

                    <span class="label dark-text">Team Members</span>
                    <input type="text" name="members" id="members" class="my-input p-2">
                    <span class="light-text info pt-1"> <strong>Pro Tip!</strong> Invite all members comma saperated</span>

                    <button class="member-submit-btn disabled-btn" id="member-submit" type="submit" disabled>Continue</button>

                    <div class="inline-block text-center mt-2" id="close-member-modal-btn">I'll do this later</div>
                </div>
            </div>
            <div class="image-section col-md-6 text-center">
                <img src="https://a.trellocdn.com/prgb/dist/images/organization/empty-board.286f8fc83e01c93ed27e.svg" alt="">
            </div>
        </div>
    </div>
</div>

resources/views/layouts/partials/_sidebar.blade.php
    <div class="sidebar">
        <ul>
            <li class="active"><i class="fa fa-trello" aria-hidden="true"></i> Boards</li>
            <li><i class="fa fa-trello" aria-hidden="true"></i> Templates</li>
            <a href="{{route('home')}}"><li><i class="fa fa-home" aria-hidden="true"></i>Home</li></a>
        </ul>
        <div class="teams">
            <p>TEAMS</p>
            <i class="fa fa-plus" aria-hidden="true" id="create-team-btn"></i>
        </div>
        <ul>
            @foreach ($teams as $team)
                <a href="{{route('showTeam',[$team->id,"null"])}}">
                    <li data-toggle="collapse" href="#collapseTeam" role="button" aria-expanded="false" aria-controls="collapseTeam">
                        <i class="fa fa-users" aria-hidden="true"></i> {{$team->name}}
                    </li>
                </a>
            @endforeach
        </ul>
    </div>